QA-4756 | Automate test scenarios for Insights and Insight explorer
celonis/celoAI-test-automation pull request #4
Opened 2024-05-22 14:34 UTC by h-janrao

2024-05-22 14:42 UTC, msharma-celonis requested changes
General overall comment.

1. if you are using 'src' structure. then I will recommend you should have tests inside the 'tests' folder. And the 'src' folder should contain modals and other helper classes.
2. If possible use the classes to represent the Modal/domain objects. You could extend from 'base_model' within FW if you decided to go with pydantic. I would recommend using pydantic.

2024-05-23 12:43 UTC, msharma-celonis requested changes
Pydantic or any other serialization is not being used and still returning the dictionary from modal classes.
Is there any specific reason of not using classes to represent domain objects or is there any reservation behind not using pydantic as recommended.

2024-05-23 15:07 UTC, msharma-celonis requested changes

2024-05-23 15:07 UTC, msharma-celonis commented on tests/insight/test_insight_explorer.py
> +        characters = "AUTOMATION".format(string.ascii_letters + string.digits)
nit: We already provide the testDataProfix as a config parameter. We should be using that as a prefix. This way it will be standardized across automation and could really help in global cleanup using the prefix if needed in the future. Also, will help in identifying the test assets created as part of automation

2024-05-23 15:10 UTC, h-janrao commented on src/py_api_test_automation_tests/client/insight_explorer_client.py
> +        return self._connection.post(_endpoint, ApiRequest().set_body(None))
Done

2024-05-23 15:10 UTC, h-janrao commented on src/py_api_test_automation_tests/client/insights_client.py
> +        return self._connection.post(_endpoint, ApiRequest().set_body(None))
Done

2024-05-23 15:12 UTC, h-janrao commented on src/py_api_test_automation_tests/modals/insight_explorer/asset.py
> +            rootNodeId="60216326-752b-4c6e-afa2-08483fcd98c4"
removed

2024-05-24 12:13 UTC, msharma-celonis commented on pyproject.toml
> +requests = "^2.31.0"
Not urgent. Please make sure to remove this dependency if you are not using requests directly.

2024-05-24 12:13 UTC, msharma-celonis commented on tests/insight/test_insights.py
> +                return item["isValid"]
Does this return a boolean?
What will happen I case of else?

2024-05-24 12:14 UTC, h-janrao commented on tests/insight/test_insights.py
> +                return item["isValid"]
Yes

2024-05-24 12:19 UTC, msharma-celonis commented on tests/insight/test_insights.py
> +                return item["isValid"]
Still we need to return something in case of else ? :)

2024-05-24 12:24 UTC, msharma-celonis approved these changes
This looks good now.

2024-05-24 12:57 UTC, merged